app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'

urlpatterns=[
    path('paper/',paper,name='paper'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
from app.views import *
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/',book,name='book'),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def book(request):
    return render(request,'book.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def paper(request):
    return render(request,'paper.html')

templates/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<center>
<body>
    
    <h1>This is first html page</h1>
    <a href="{% url 'app1:paper' %}">Go to Rohi page</a>
</center>
</body>
</html>

templates/paper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
        <center>
        <h1>Today is thursday</h1>
        <a href="{% url 'book' %}">Navigate to DHONI</a>
        </centre>
</body>
</html>